// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbvdmxozjtpfrfkuplxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidmRteG96anRwZnJma3VwbHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTI3NDQsImV4cCI6MjA3MDk4ODc0NH0.qEkrdY1K1DhEFxKCfLDdh78b7rpaNoIpGych--Cr3Qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});